### PR TITLE
Fixing the syncing of upstream/main to openshift/release-next branch

### PR DESCRIPTION
**Pull request by rupalibehera**
Switching master to main, adding OPENSHIFT_REMOTE to test changes locally, this script is fixed to merge upstream changes to
midstream.
This is will resolve https://issues.redhat.com/browse/SRVKP-1338

### CODE REVIEW

**Comment by rupalibehera** [comment]
@khrm @savitaashture, Would you guys be able to review this ?

**Comment by piyush-garg** [comment]
Should we also add nightly pipeline and triggers release yaml?

**Comment by rupalibehera** [comment]
> Should we also add nightly pipeline and triggers release yaml?

Where should these yaml go ?

**Comment by khrm** [comment]
Let's add nightly yaml to kodata as part of patch.

**Comment by piyush-garg** [comment]
@rupalibehera Basically here https://github.com/tektoncd/operator/tree/main/cmd/openshift/kodata we need to put the nightly release.yaml or the last released release.yaml from the respective forks

**Comment by rupalibehera** [comment]
> @rupalibehera Basically here https://github.com/tektoncd/operator/tree/main/cmd/openshift/kodata we need to put the nightly release.yaml or the last released release.yaml from the respective forks

Could you point me to any example release.yaml to check how does it look ?

**Comment by rupalibehera** [comment]
> > @rupalibehera Basically here https://github.com/tektoncd/operator/tree/main/cmd/openshift/kodata we need to put the nightly release.yaml or the last released release.yaml from the respective forks
> 
> Could you point me to any example release.yaml to check how does it look ?

@pgarg are we talking about the CPaas release.yaml ?

**Comment by khrm** [comment]
@rupalibehera No. We are talking of triggers and pipelines release.yaml. e.g. https://github.com/openshift/tektoncd-pipeline/blob/release-v0.20.1/openshift/release/tektoncd-pipeline-v0.20.1.yaml

**Comment by piyush-garg** [comment]
@rupalibehera In the old repo, we were doing like this https://github.com/openshift/tektoncd-pipeline-operator/blob/master/openshift/release/update-to-head.sh#L22

We need to do the same for pipelines and triggers here with the little location change

**Comment by rupalibehera** [comment]
ok thanks for the clarification

**Comment by rupalibehera** [comment]
@khrm Could you please review this ?

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by savitaashture** [comment]
@rupalibehera did we handle nightly yamls as piyush suggested?
Because i don't see it in PR

**Comment by rupalibehera** [comment]
> @rupalibehera did we handle nightly yamls as piyush suggested?
> Because i don't see it in PR

I think so @khrm is taking care of that, he was discussing with Nikhil regrading where to put it.

**Review by khrm — APPROVED** [review]

**Pull request merged**
