### PR TITLE
Update clustertasks with HOME env

### PR DESCRIPTION
**Pull request by piyush-garg**
This will update clustertask bsed on release branches
of release-v0.28

s2i clustertasks have HOME env in generate step to
not show warning

### CODE REVIEW

**Review by concaf — APPROVED** [review]

**Review by rupalibehera — APPROVED** [review]

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Review by savitaashture — APPROVED** [review]

**Comment by nikhil-thomas** [comment]
closing this as this change will be automatically pulled by create-release-branch script.

**Pull request closed without merging**
